### ISSUE TITLE
无法唤起键盘

### ISSUE THREAD

**Issue by dd178** [git-xiaocao/pixiv_func_mobile#15]
WebView是platformwebview，Android System WebView版本100.0.4896.127，手机是红米k40，miui13.0.3
另外，那个‘从剪切板登录’怎么使用？cookie？在哪抓？抓什么？

**Comment by git-xiaocao** [comment]
可以尝试在别的地方输入好账号密码然后复制黏贴。
下一个版本就不打算再用webview输入了，而是在flutter在输入完用js填充到webview里。

**Comment by git-xiaocao** [comment]
从剪切板登录需要在别的地方登录app然后长按头像复制登录信息

**Comment by git-xiaocao** [comment]
当然也可以自己抓 不过不是web端 没有cookie

**Comment by dd178** [comment]
> 可以尝试在别的地方输入好账号密码然后复制黏贴。 下一个版本就不打算再用webview输入了，而是在flutter在输入完用js填充到webview里。

试过复制粘贴了，也不行，我还是等更新吧

**Comment by git-xiaocao** [comment]
已在`new`分支解决(未发布)
