### ISSUE TITLE
隐藏选定的标签

### ISSUE THREAD

**Issue by grishiit** [git-xiaocao/pixiv_func_mobile#17]
我为我的中文感到抱歉（我使用翻译）。

如果能够隐藏有用户定义的标签的帖子就更好了

提前感谢您!

**Comment by git-xiaocao** [comment]
你是指 隐藏一些 包含你自定义的`tag`的作品吗 (比如`#原神` `#Genshin Impact`)
你也可以使用英文 由我来翻译

**Comment by grishiit** [comment]
Yes, that's exactly what I mean.

**Comment by git-xiaocao** [comment]
将在new分支中新增该功能

**Comment by git-xiaocao** [comment]
`new`分支中已经新增该功能,但是还没有做国际化(i18n)支持
