### ISSUE TITLE
Open links

### ISSUE THREAD

**Issue by lucas-04** [git-xiaocao/pixiv_func_mobile#20]
Open links share from another apps

**Comment by git-xiaocao** [comment]
custom scheme?

**Comment by git-xiaocao** [comment]
Similar to "https://pixiv.net/users/12345"
Click on the prompt to open with "Pixiv Func"?

**Comment by lucas-04** [comment]
> Similar to "https://pixiv.net/users/12345"
> Click on the prompt to open with "Pixiv Func"?

Yes

**Comment by git-xiaocao** [comment]
将在`new`分支中新增该功能
