### ISSUE TITLE
关于软件的建议

### ISSUE THREAD

**Issue by VCE1** [git-xiaocao/pixiv_func_mobile#23]
相对于右上角保存按钮，我更希望使用长按保存图片

**Comment by VCE1** [comment]
版本号0.8.0

**Comment by VCE1** [comment]
新版本已解决，有多个版本搞混了

**Comment by git-xiaocao** [comment]
> 相对于右上角保存按钮，我更希望使用长按保存图片

这是设计师做的

**Comment by git-xiaocao** [comment]
可以点单个图片上的下载按钮
后面会加一些功能 比如检查是不是已经下载过(存下载记录) 重复下载(删除之前的)

**Comment by VCE1** [comment]
了解了。那么建议在功能里多加长按下载这一功能，这样存图会很方便。
