### ISSUE TITLE
图片搜索筛选功能失效

### ISSUE THREAD

**Issue by VCE1** [git-xiaocao/pixiv_func_mobile#24]
搜索关键字或标签，发现没办法按收藏数量排序。不止如此，图片筛选的选项都没有反应。
![IMG_20220729_180830](https://user-images.githubusercontent.com/79588027/181737334-77123b43-bc35-42c5-a1e6-a66a629f7ddb.jpg)

**Comment by git-xiaocao** [comment]
有的呀

**Comment by git-xiaocao** [comment]
有一种可能 你从标签里面点进去的

**Comment by git-xiaocao** [comment]
![image](https://user-images.githubusercontent.com/76673990/181816021-280bb726-f163-43f8-9ef3-08c55d934a99.png)
