### ISSUE TITLE
Was it necessary to remove the English translation?

### ISSUE THREAD

**Issue by lucas-04** [git-xiaocao/pixiv_func_mobile#25]

**Comment by git-xiaocao** [comment]
新版本的i18n目前还没开始做
计划做 简体中文 日本语 英语 俄语

**Comment by lucas-04** [comment]
I can translate from english to portuguese and spanish, if you want to add these two languages.

**Comment by DIXLOR15** [comment]
I can translate from English To Russian

**Comment by git-xiaocao** [comment]
已经做好准备了 在[i18n_translations.dart#L216](https://github.com/git-xiaocao/pixiv_func_mobile/blob/new/lib/app/i18n/i18n_translations.dart#L216) 中
我将在 加载图 封面图 等 画完之后 添加翻译 并发布1.0.0正式版本

**Comment by DIXLOR15** [comment]
I created preview Russian Translation. In some items of the menu, the Russian version of the translation does not fit 

![Screenshot_20220823-023147_Pixiv Func](https://user-images.githubusercontent.com/36164693/186013386-b4c52d60-ac3d-46ab-a783-1e474bbbf933.png)
![Screenshot_20220823-021804_Pixiv Func](https://user-images.githubusercontent.com/36164693/186013405-357a01a0-de33-45ab-8384-c325dbbede8a.png)

**Comment by git-xiaocao** [comment]
俄语比简体中文长这么多吗?
最好是保证意思不变的情况下尽量短
有写地方需要硬编码

**Comment by git-xiaocao** [comment]
如果不熟悉简体中文的话 可以等我做完英语之后从英语翻译到俄语

**Comment by git-xiaocao** [comment]
常量名和实际用来显示的英语是有一些差距的

**Comment by git-xiaocao** [comment]
@DIXLOR15 我已经添加了en_US翻译 你可以看看

**Comment by DIXLOR15** [comment]
Yes, I saw that. Some of the words I will have to leave in English, since there are no short and clear alternatives in Russian.

**Comment by git-xiaocao** [comment]
@DIXLOR15 嗯 可以PR了

**Comment by DIXLOR15** [comment]
I add a PR

**Comment by git-xiaocao** [comment]
i18n都添加了
