### ISSUE TITLE
首次打开应用时文本被数字替代的问题

### ISSUE THREAD

**Issue by miniGU2021** [git-xiaocao/pixiv_func_mobile#28]
下载并安装应用后，首次打开应用都出现了文本被数字替代的问题。我测试过的3个apk均出现了以下状况。
1.0.0-beta31 app-arm64-v8a-release.apk
1.0.0-beta31 app-release.apk
1.0.0-beta30 app-release.apk
我翻阅了readme和About下方标注的网站https://pixiv.xiaocao.moe/#/pixiv-func/mobile, 没有关于这些数字的介绍.我不知道这是刻意的设计还是文本替换的问题. 它极大地影响了我的使用体验.  如果是bug的话尽快修复吧. 以下是应用的截图和我手机的机型.
![762AC8AA4C1E01F953785BB96FCF48AB](https://user-images.githubusercontent.com/44805461/185850277-d834d874-f553-4b0c-b3d1-1e4f312f6a4a.jpg)
![F0F0CFA1C476B36FD0164F3F3B4BACD8](https://user-images.githubusercontent.com/44805461/185850325-e4dda95e-9760-4a6c-bcd1-450cafbce6b2.jpg)
![7A56C0F3F666DAFB7649EC02CE383A13](https://user-images.githubusercontent.com/44805461/185850340-3fecd905-d8e5-42d4-a771-e8fe42be5a97.jpg)
![531F224156BB4F0DB04CDD506201AA05](https://user-images.githubusercontent.com/44805461/185857467-b680fec7-a92b-4ee0-8db6-fa83d704b50e.jpg)

**Comment by git-xiaocao** [comment]
[i18n_translations.dart#L216](https://github.com/git-xiaocao/pixiv_func_mobile/blob/new/lib/app/i18n/i18n_translations.dart#L216)
其实是i18n还没添加翻译 用了系统默认语言且不是zh_CN之后就变成了数字
https://github.com/git-xiaocao/pixiv_func_mobile/issues/25#issuecomment-1221516673

**Comment by git-xiaocao** [comment]
你可以使用beta32切换成简体中

**Comment by miniGU2021** [comment]
> 

好快的新版本. 这几个架构有区别吗

**Comment by git-xiaocao** [comment]
> > 
> 
> 好快的新版本. 这几个架构有区别吗

这只是分包减少大小的 现在的手机都是arm64了 arm32的很少 x86_64一般是模拟器和平板
最大的那个包是所有架构都打包了

**Comment by git-xiaocao** [comment]
i18n都添加了
