### ISSUE TITLE
Japanese Menu text & Font fix...

### ISSUE THREAD

**Issue by reindex-ot** [git-xiaocao/pixiv_func_mobile#35]
![Screenshot_2022-08-28-16-30-02-64_e52a77fb31bde51e0d2080a7c03433db](https://user-images.githubusercontent.com/32851879/187063333-23cbff96-04c6-443e-95fb-c34e69111bda.jpg)

There is a problem with broken text in the menu. Otherwise, please change the font used in the theme for Japanese.

Fix here!
illust: イラス→イラスト
user: ユーザ→ユーザー

**Comment by git-xiaocao** [comment]
这个问题我已经注意到了 还有好多地方文本都溢出了 如果你看得懂简体中文的话可以先使用简体中文

**Comment by git-xiaocao** [comment]
你可以看看新版本还有没有这个问题

**Comment by balawolf** [comment]
@git-xiaocao A related problem is that the last letter of the `フォロー中` text of a user I am following is missing and becomes `フォロー`.
|1|2|3|
|---|---|---|
|![Screenshot_20220906-164923(1)](https://user-images.githubusercontent.com/111877042/188609429-ebc72faa-6766-40ee-9c4d-cbd0203350b0.png)|![Screenshot_20220906-191810(1)](https://user-images.githubusercontent.com/111877042/188611242-d8cecd8d-5c9f-453b-aa59-9ee97b75a1cb.png)|![Screenshot_20220906-191821(1)](https://user-images.githubusercontent.com/111877042/188611258-e44ec9aa-014b-4510-8ff4-b38f3806a84d.png)|

`フォロー` → `フォロー中`

**Comment by git-xiaocao** [comment]
新版本发布了release

**Comment by balawolf** [comment]
@git-xiaocao This issue has been fixed, thank you!
