### ISSUE TITLE
Add widget support to show recommended works

### ISSUE THREAD

**Issue by Losvayne** [git-xiaocao/pixiv_func_mobile#39]
Pls add widget support just like pixiv-shaft by CieuLiSA.

**Comment by git-xiaocao** [comment]
请给个图例

**Comment by Losvayne** [comment]
[Pixiv-shaft by CieuLiSA](https://github.com/CeuiLiSA/Pixiv-Shaft)

**Comment by Losvayne** [comment]
> [Pixiv-shaft by CieuLiSA](https://github.com/CeuiLiSA/Pixiv-Shaft)

![Screenshot_2022-09-01-21-37-28-236](https://user-images.githubusercontent.com/90143387/188259775-03982531-b98a-4677-b865-a7bc5853aaaa.jpeg)

**Comment by Losvayne** [comment]
This is my home screen with pixiv-shaft recommended widgets

**Comment by Losvayne** [comment]
This is what i can tell you at the moment

**Comment by Losvayne** [comment]
Pls elaborate what details you want

**Comment by Losvayne** [comment]
With this widget support added your app will become an absolute pixiv replacement

**Comment by git-xiaocao** [comment]
你指的是android桌面小部件(AppWidget)吗
https://developer.android.com/guide/topics/appwidgets?hl=zh-cn

**Comment by Losvayne** [comment]
Yeah

**Comment by git-xiaocao** [comment]
![Screenshot_2022-09-16-02-41-11-126_com.miui.home.jpg](https://user-images.githubusercontent.com/76673990/190484124-23797b22-e24b-479b-bb38-def520ae8a8b.jpg)

目前初步测试了一下(AppWidget)

**Comment by git-xiaocao** [comment]
![Screenshot_2022-09-18-00-04-21-736_com.miui.home.jpg](https://user-images.githubusercontent.com/76673990/190865959-c03453e5-db62-4f33-9adb-f512fc70543e.jpg)

已完成(在beta40版本)

**Comment by git-xiaocao** [comment]
@Losvayne
