### ISSUE TITLE
How to see my past favourites/bookmarks?

### ISSUE THREAD

**Issue by luci9t** [git-xiaocao/pixiv_func_mobile#41]
Might be a dumb question but can't find how to see my past favourites. The "My pixiv" menu is empty.

**Comment by git-xiaocao** [comment]
好像 确实是我忘记了这个选项 因为我没有my pixiv

**Comment by luci9t** [comment]
It's ok if it's in development, I understand the application is in beta. Thanks for the application either way.

这是通过谷歌翻译, 如果它正在开发中也没关系, 我知道该应用程序处于测试阶段。感谢您的申请。

**Comment by git-xiaocao** [comment]
我会在下个版本补齐这个功能

**Comment by luci9t** [comment]
好的，非常感谢
