### ISSUE TITLE
日语环境中的布局干扰。

### ISSUE THREAD

**Issue by Katsuyuki-Karasawa** [git-xiaocao/pixiv_func_mobile#43]
以下领域似乎受到了干扰
在所有语言中检查了`ja_JP`
https://github.com/git-xiaocao/pixiv_func_mobile/blob/204e013ac0eb436229eaac3b7da9e87053f02d23/lib/app/i18n/i18n_translations.dart#L520

![mosaic_20220913173109](https://user-images.githubusercontent.com/70247011/189852547-d490f103-8304-496a-b744-bb674227de61.png)
![Screenshot_20220913-172455_Pixiv_Func-02](https://user-images.githubusercontent.com/70247011/189852554-4ce3b4bd-5e6c-4c5f-94d1-ffd5fd37c037.jpg)

**Comment by git-xiaocao** [comment]
这个问题我已经解决了(还没有推送) 是一个bug 与语言无关

**Comment by git-xiaocao** [comment]
TabBar在可滚动的状态下 大小不固定 Stack会把icon和text重叠

**Comment by Katsuyuki-Karasawa** [comment]
@git-xiaocao 
这里也出现了同样的布局坍塌。
请纠正同样的问题。

https://github.com/git-xiaocao/pixiv_func_mobile/blob/4de3ccfbe8cee087bb4887b31eefdddf24874637/lib/app/i18n/i18n_translations.dart#L616

![](https://media.discordapp.net/attachments/757393787730395146/1019225370916028466/Screenshot_20220913-213509_Pixiv_Func-01.jpg)
![](https://media.discordapp.net/attachments/757393787730395146/1019225370643402802/Screenshot_20220913-213509_Pixiv_Func.png?width=548&height=1217)

**Comment by git-xiaocao** [comment]
好的

**Comment by git-xiaocao** [comment]
这个地方是我指定了固定宽度 现在需要把他改成获取文本宽度

**Comment by git-xiaocao** [comment]
新版本发布了release

**Comment by git-xiaocao** [comment]
如果问题解决了请 Close
