### ISSUE TITLE
追随者的地位是一样的

### ISSUE THREAD

**Issue by Katsuyuki-Karasawa** [git-xiaocao/pixiv_func_mobile#44]
目前，Followed和Follow(Not Follow)的状态在所有屏幕上都是一样的，或者不清楚它们是否在跟踪。
这是相当严重的问题，需要紧急解决。
![](https://media.discordapp.net/attachments/757393787730395146/1019254823075455047/Screenshot_20220913-233331_Pixiv_Func-01.jpg?width=759&height=1217)

**Comment by git-xiaocao** [comment]
好的 了解了 谢谢

**Comment by git-xiaocao** [comment]
![image](https://user-images.githubusercontent.com/76673990/189979945-ef512e82-e819-4135-80ba-936c3c232fe4.png)

![image](https://user-images.githubusercontent.com/76673990/189980374-31430569-d081-4bec-a312-ffa4e33902dd.png)

![image](https://user-images.githubusercontent.com/76673990/189980949-d360b210-6706-4a53-893b-49ea4bb39a92.png)



请问这算是解决了吗

**Comment by git-xiaocao** [comment]
新版本发布了release

**Comment by git-xiaocao** [comment]
如果问题解决了请 Close
