### ISSUE TITLE
没有许可证的迹象

### ISSUE THREAD

**Issue by Katsuyuki-Karasawa** [git-xiaocao/pixiv_func_mobile#45]
没有许可证似乎不是一个很好的状态。
我不认为MIT有什么问题，但如果你能给予我们某种许可就更好了，不管它是什么
![image](https://user-images.githubusercontent.com/70247011/190038156-b6e166a0-028f-4179-a19c-71ced800ff3f.png)

**Comment by git-xiaocao** [comment]
原本是AGPL 不过在重构的时候忘记添加

**Comment by git-xiaocao** [comment]
如果你有 mypixiv(好P友) 可以帮我测试下新增的功能 因为我的账号没有mypixiv😂

**Comment by Katsuyuki-Karasawa** [comment]
@git-xiaocao 
我不知道mypixiv是什么，但我会尽可能地帮助你。

**Comment by git-xiaocao** [comment]
就是好P友

**Comment by git-xiaocao** [comment]
已经添加了AGPL
