### ISSUE TITLE
关于Issue

### ISSUE THREAD

**Issue by git-xiaocao** [git-xiaocao/pixiv_func_mobile#50]
打开新的Issue时可以使用机器翻译,翻译为简体中文(English -> 简体中文)
因为我不会英语,在`GitHub Android`上也不方便翻译

**Comment by Katsuyuki-Karasawa** [comment]
是否无法访问例如[deepl](https://www.deepl.com/)？

**Comment by Katsuyuki-Karasawa** [comment]
@git-xiaocao 
我做了这样的东西，你觉得怎么样？
如果你愿意，我可以制作其他的模板，并给你发送一个PR。
我不知道这是否会有帮助，但至少它看起来没有以前那么繁重。
https://github.com/Katsuyuki-Karasawa/pixiv_func_mobile/blob/new/.github/ISSUE_TEMPLATE/bug-report.md
https://github.com/Katsuyuki-Karasawa/pixiv_func_mobile/issues/new?assignees=&labels=bug&template=bug-report.md&title=

**Comment by git-xiaocao** [comment]
这个我自己来做一下吧(github不太熟练)
