### ISSUE TITLE
增加深度链接。

### ISSUE THREAD

**Issue by Katsuyuki-Karasawa** [git-xiaocao/pixiv_func_mobile#51]
`www.pixiv.me` `pixiv.me` 深层链接似乎应该在那里
![](https://cdn.discordapp.com/attachments/757393787730395146/1019777021406097429/Screenshot_20220914-231549_-01.jpg)

**Comment by git-xiaocao** [comment]
深度链接怎么了

**Comment by Katsuyuki-Karasawa** [comment]
尚未实施。
这是一张PixEZ图像。

**Comment by git-xiaocao** [comment]
此项目支持深度链接的pixiv.net www.pixiv.net

**Comment by git-xiaocao** [comment]
![Screenshot_2022-09-15-13-28-37-027_com.github.android.jpg](https://user-images.githubusercontent.com/76673990/190321909-91504f38-6404-4b85-82af-59b57305f280.jpg)
