### ISSUE TITLE
早期的语言错误。

### ISSUE THREAD

**Issue by Katsuyuki-Karasawa** [git-xiaocao/pixiv_func_mobile#52]
语言被强制为中文而不是默认设置中选择的语言的现象。
另外，默认屏幕中不是检查表而仍然是切换的那部分需要改正
![](https://cdn.discordapp.com/attachments/757393787730395146/1020137978816901200/Screenshot_20220916-100125_Pixiv_Func.png)

**Comment by git-xiaocao** [comment]
好的 待会起床了看看

**Comment by git-xiaocao** [comment]
![image](https://user-images.githubusercontent.com/76673990/190556995-81e9c34d-5f0f-46eb-9354-b40733b00336.png)

你指的是这行代码吗

**Comment by git-xiaocao** [comment]
https://user-images.githubusercontent.com/76673990/190557034-d134022b-38c7-4e75-a005-a82a07c49302.mp4

切换目前没有问题

**Comment by git-xiaocao** [comment]
因为不同的语言中 相同的文字 高度 形状可能不一样 会导致UI有所变化 所以我指定了默认为中文字体

**Comment by Katsuyuki-Karasawa** [comment]
显然，在中文中被修复是取决于环境的（在Beta37中可以重现，但在Beta38中似乎已经被修复）。
然而，这个切换有点微妙，所以根据设置屏幕来检查可能会更好（对不起，我不顾一切地给你发了一个无法重复的问题）。
