### ISSUE TITLE
[bug]小说不再加载。

### ISSUE THREAD

**Issue by Katsuyuki-Karasawa** [git-xiaocao/pixiv_func_mobile#57]
**Describe the bug(描述这个bug)**
小说不能再被加载（也许是api？）

**To Reproduce(重现步骤)**
打开小说（可能发生在所有小说中）。

**Expected behavior(预期行为)**
修订后，纳入了小说。

**Screenshots**
![](https://cdn.discordapp.com/attachments/757393787730395146/1039904104455090336/Screenshot_20221109-230728_Pixiv_Func.png)

**OS:**
Device: 紅米 Note 10 Pro
OS: Android 13 & 12L

**Additional context**
没

**Comment by git-xiaocao** [comment]
可能是api或者小说网页变动了

**Comment by git-xiaocao** [comment]
几天前修复了

**Comment by Katsuyuki-Karasawa** [comment]
用β49，它没有工作，但看起来它还没有提交?
@git-xiaocao

**Comment by Katsuyuki-Karasawa** [comment]
相反，这是一个在你不知情的情况下留白的错误（即使你只是搜索它也不行）。
![Screenshot_20221125-123049_Pixiv Func-01](https://user-images.githubusercontent.com/70247011/203896036-58884fbc-0697-49aa-9741-fe0d8c13e5e4.jpeg)

**Comment by git-xiaocao** [comment]
好的 我知道了

**Comment by git-xiaocao** [comment]
已修复

**Comment by Katsuyuki-Karasawa** [comment]
感谢你的辛勤工作
