### ISSUE TITLE
[feature]Max download task running

### ISSUE THREAD

**Issue by nguyenzzz** [git-xiaocao/pixiv_func_mobile#60]
**Is your feature request related to a problem? Please describe.**
My device is lagging when downloading so many images. So i need to change how many task to download at time

**Describe the solution you'd like**
Hope you add Max download task running like PixEz (screenshot bellow)

**Additional context**
![Screenshot_20221201-221320_Trebuchet~2](https://user-images.githubusercontent.com/90515563/205090719-bc506892-2245-4ab4-828f-21f4ad494542.png)

**Comment by git-xiaocao** [comment]
好的

**Comment by git-xiaocao** [comment]
已添加该功能

**Comment by nguyenzzz** [comment]
> 已添加该功能

Thank you🥰. Now you can close request
