### ISSUE TITLE
无法直连，图片无法加载

### ISSUE THREAD

**Issue by YingShangYi** [git-xiaocao/pixiv_func_mobile#62]
![S21220-01345761](https://user-images.githubusercontent.com/116354340/208486565-557da555-1525-42f6-a738-b64c3533dfd6.png)
，，嗯——这是在我切换了图片源之后发生的故障，原本是可以正常使用的，尝试重装软件却并没有作用

**Comment by git-xiaocao** [comment]
截图图片源

**Comment by YingShangYi** [comment]
![S21220-13410758](https://user-images.githubusercontent.com/116354340/208593019-ebb465dd-da35-4b33-bf82-c4dc043f9979.png)
今天它好像能载出一半的图了XD
![S21220-13410268](https://user-images.githubusercontent.com/116354340/208593101-0ba75939-f52f-45b3-9edc-795b8865c6a7.png)

**Comment by YingShangYi** [comment]
![S21220-13410758](https://user-images.githubusercontent.com/116354340/208593246-4216b064-3295-4d83-8dc7-c01cb5245cf0.png)
今天它好像能载出一半的图了XD

**Comment by YingShangYi** [comment]
![S21220-13495932](https://user-images.githubusercontent.com/116354340/208594112-7223ef8a-1e27-45f3-988d-f524eb9011c5.png)

**Comment by git-xiaocao** [comment]
![Screenshot_2022-12-20-20-07-49-157_moe.xiaocao.pixiv.jpg](https://user-images.githubusercontent.com/76673990/208663627-27aa534d-d8f6-4acc-a77a-c42ff0e1e2e9.jpg)

**Comment by YingShangYi** [comment]
额，，是叫我按照上面设置吗，？我尝试了一下，没有起作用

**Comment by git-xiaocao** [comment]
试试自定义 i.pixiv.re

**Comment by YingShangYi** [comment]
哦～，可以直连了，谢谢宝੭ ᐕ)੭*⁾⁾
