### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by 2354452553** [git-xiaocao/pixiv_func_mobile#63]
**Describe the bug(描述这个bug)**
Describe the bug in Chinese/English.
用中文/英文描述bug.
登录账号以后返回界面提示登录成功，然而并没有跳转到app界面，他还会卡在登录这里。
If you can speak Chinese, please use Chinese, or use Google/DeepL Translate (Please use English to translate to Chinese, do not use other languages to translate to Chinese)

**To Reproduce(重现步骤)**
Steps to reproduce the behavior(重现行为的步骤):
1. 安装软件
2. 打开软件
3. 一切默认
4. 手机开着vpn
5. 登录成功
6. 卡在注册 或 登录界面

**Expected behavior(预期行为)**
对您期望发生的事情进行清晰简洁的描述.

**Screenshots**
If applicable, please add screenshots/videos to help explain your problem.
如果可以的话请添加截图/视频.

https://user-images.githubusercontent.com/73208658/209600185-f2442ac5-f685-4383-8cda-c42266029925.mp4

**OS:**
 - Name: [e.g. Redmi9]
 - Version [e.g. Android 12]

**Additional context**
Add any other context/log about the problem here.
在此处添加有关该问题的任何其他上下文/日志.

**Comment by git-xiaocao** [comment]
我知道了 等我下午起床吃完饭就修复

**Comment by 2354452553** [comment]
> 我知道了 等我下午起床吃完饭就修复

快特么起来修bug

**Comment by Katsuyuki-Karasawa** [comment]
I don't know why you are so angry, but since it is open source, why don't you fix it yourself and send a Pull Request?

If you restart the app, you'll be able to log in, so just relax for now.
@2354452553

**Comment by 2354452553** [comment]
> I don't know why you are so angry, but since it is open source, why don't you fix it yourself and send a Pull Request?
> 
> If you restart the app, you'll be able to log in, so just relax for now. @2354452553

No, no, I was kidding.

**Comment by wdnmd030** [comment]
> was

🤣🤣🤣

**Comment by git-xiaocao** [comment]
已修复
