### ISSUE TITLE
Buid apk

### ISSUE THREAD

**Issue by lucas-04** [git-xiaocao/pixiv_func_mobile#65]
I try to compile but get a erro

$ flutter build apk --obfuscate --split-debug-info=build/split-debug-info/

💪 Building with sound null safety 💪

FAILURE: Build failed with an exception.

* Where:
Build file '/home/lucas/Música/pixiv_func_mobile-1.0.0-beta53-59/android/app/build.gradle' line: 61

* What went wrong:
A problem occurred evaluating project ':app'.
> path may not be null or empty string. path='null'

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Running Gradle task 'assembleRelease'...                            4,0s
Gradle task assembleRelease failed with exit code 1

**Comment by git-xiaocao** [comment]
缺少Android签名

**Comment by lucas-04** [comment]
> 缺少Android签名

how do i get this?

**Comment by git-xiaocao** [comment]
注释掉此文件的57到70行
[pixiv_func_mobile/android/app/build.gradle](https://github.com/git-xiaocao/pixiv_func_mobile/blob/beta/android/app/build.gradle)

![image](https://user-images.githubusercontent.com/76673990/212028388-0c25581b-47b6-4bc8-a548-b0f6e5de4eb1.png)

**Comment by lucas-04** [comment]
Another error

flutter build apk --obfuscate --split-debug-info=build/split-debug-info/

💪 Building with sound null safety 💪


FAILURE: Build failed with an exception.

* Where:
Build file '/home/lucas/Música/pixiv_func_mobile-1.0.0-beta53-59/android/app/build.gradle' line: 77

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not get unknown property 'release' for SigningConfig container of type org.gradle.api.internal.FactoryNamedDomainObjectContainer.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 57s
Running Gradle task 'assembleRelease'...                           60,5s
Gradle task assembleRelease failed with exit code 1

**Comment by git-xiaocao** [comment]
注释掉报错的那一行

**Comment by git-xiaocao** [comment]
74行和77行

**Comment by lucas-04** [comment]
> 注释掉报错的那一行

Not work.

Maybe i try it later.
