### ISSUE TITLE
[feature]建议增加r18快捷开关

### ISSUE THREAD

**Issue by qimingnan17** [git-xiaocao/pixiv_func_mobile#66]
比如退出软件自动关闭r18每次需要手动开启等方式

**Comment by qimingnan17** [comment]
最好也可以在关闭r18功能后隐藏排行中按钮

**Comment by git-xiaocao** [comment]
哪里的r18 按理说不会关闭呀

**Comment by git-xiaocao** [comment]
懂了 你说的是给软件关闭r18

**Comment by git-xiaocao** [comment]
你点app设置那里 个人头像点进去 账号设置那里还有个设置 ![Screenshot_2023-02-20-15-27-23-076_moe.xiaocao.pixiv.jpg](https://user-images.githubusercontent.com/76673990/220039728-3118d23c-2c6f-4514-8b66-eb129425e7d2.jpg)
![Screenshot_2023-02-20-15-27-39-215_moe.xiaocao.pixiv.jpg](https://user-images.githubusercontent.com/76673990/220039757-2fbbc952-a4a9-44d5-8c9b-07c429f1453a.jpg)

**Comment by qimingnan17** [comment]
谢谢作者解答

**Comment by qimingnan17** [comment]
希望能加一个更外面的按钮开关最好就是二级的地方

**Comment by git-xiaocao** [comment]
这个是跟账号绑定的 修改的是账号的r18开关
跟你去网页修改是一样的

**Comment by qimingnan17** [comment]
那能加一个本地的吗打开开关只进行过滤不对账号信息修改

**Comment by git-xiaocao** [comment]
可以 等我之后更新吧

**Comment by qimingnan17** [comment]
谢谢

**Comment by git-xiaocao** [comment]
已更新
