### ISSUE TITLE
咱就是说是不是弄错了

### ISSUE THREAD

**Issue by qimingnan17** [git-xiaocao/pixiv_func_mobile#72]
![Screenshot_20230429_074020.jpg](https://user-images.githubusercontent.com/97949665/235270379-29842522-b2a5-45c3-9580-ad95c85b1cbb.jpg)版本号出错![Screenshot_20230429_074020.jpg](https://user-images.githubusercontent.com/97949665/235270404-cdaa1b14-7461-4d87-8b92-99d2bb6de2df.jpg)是不是只加了一会开关![Screenshot_20230429_074037_moe.xiaocao.pixiv_edit_89574459394664.jpg](https://user-images.githubusercontent.com/97949665/235270441-9356ffee-d81d-48e9-8a57-6b8f16bc5e14.jpg)

**Comment by qimingnan17** [comment]
![Screenshot_20230429_074028_moe.xiaocao.pixiv_edit_89583106388934.jpg](https://user-images.githubusercontent.com/97949665/235270509-e0211ebb-2cde-40d5-9d7a-febf70c88bec.jpg)

**Comment by git-xiaocao** [comment]
这个开关要刷新一下
版本号是弄错了

**Comment by git-xiaocao** [comment]
这个功能 不打算刷新APP 以后都是手动刷新/重启APP 后生效
