### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by Yan546** [git-xiaocao/pixiv_func_mobile#74]
beta60，多P图片(横图)滑动时图片分隔线会闪烁

**Comment by git-xiaocao** [comment]
可以给个视频嘛

**Comment by Yan546** [comment]
> 可以给个视频嘛

https://wwyg.lanzouo.com/iatHo0ww0tyd

**Comment by git-xiaocao** [comment]
github是能直接上传视频的

**Comment by git-xiaocao** [comment]
看了一下 在明亮主题下确实会闪 但是我的代码中没有分割线 这可能是一个flutter的bug

**Comment by Yan546** [comment]
> github是能直接上传视频的

手机上不知道怎么回事，点图片那个图标选文件拉取不到应用，只有相机可用，MIUI14

**Comment by Yan546** [comment]
> > GitHub是能直接上传视频的
> 
> 手机上不知道怎么回事，点图片那个图标选文件拉取不到应用，只有相机可用，MIUI14

知道了，自带浏览器的问题😓

**Comment by Yan546** [comment]
> > GitHub是能直接上传视频的
> 
> 手机上不知道怎么回事，点图片那个图标选文件拉取不到应用，只有相机可用，MIUI14

知道了，自带浏览器的问题😓

**Comment by git-xiaocao** [comment]
最新版本的Flutter 似乎解决了该问题 请查看最新版本的Release

**Comment by Yan546** [comment]
还是有，你自己看看吧插画uid106277497
