### ISSUE TITLE
登录无法唤起键盘

### ISSUE THREAD

**Issue by MarilynPalmer** [git-xiaocao/pixiv_func_mobile#8]
系统内置浏览器内无法唤起键盘

**Comment by MarilynPalmer** [comment]
安卓12 Android System WebView
版本 98.0.4758.87

**Comment by xiao-cao-x** [comment]
> 安卓12 Android System WebView
> 版本 98.0.4758.87

你指的系统浏览器 是什么意思？
APP不应该跳转到系统浏览器

**Comment by xiao-cao-x** [comment]
我想起来了 我之前那个手机也是vivo的(iqoo u1x) 点登录框得一直点 点很多次才能弹出来
换手机了把这事给忘了

**Comment by xiao-cao-x** [comment]
我想起来了 我之前那个手机也是vivo的(iqoo u1x) 点登录框得一直点 点很多次才能弹出来
换手机了把这事给忘了

**Comment by MarilynPalmer** [comment]
就是跳转到PlatformWebView的网页没法唤起键盘

**Comment by xiao-cao-x** [comment]
那你点下编辑框看看 是弹出来一下又缩回去嘛，如果是的话就反复点编辑框知道他不缩回去为止
我再想办法兼容vivo

**Comment by MarilynPalmer** [comment]
点编辑框除了有个待输入的符号之外没反应

**Comment by git-xiaocao** [comment]
已在`new`分支解决(未发布)
